# Generated by Django 2.1.7 on 2019-12-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190927_1511'),
        ('main', '0003_auto_20190124_1800'),
    ]

    operations = [
    ]
